name:                telegram-types
version:             0.1.0.0
github:              "poscat0x04/telegram-types"
license:             BSD3
author:              "Poscat"
maintainer:          "poscat@mail.poscat.moe"
copyright:           "2020 Poscat"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/poscat0x04/telegram-types#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- filepath
- aeson
- deriving-aeson
- unordered-containers
- open-union
- mime-types
- servant
- servant-multipart
- lens
- generic-lens

library:
  source-dirs: src
  exposed-modules:
    - Web.Telegram.Types
    - Web.Telegram.Types.Lens
    - Web.Telegram.Types.Stock
    - Web.Telegram.Types.Interaction
    - Web.Telegram.Types.Inline
    - Web.Telegram.Types.Input
    - Web.Telegram.Types.Update
    - Web.Telegram.Types.UpdateType

tests:
  telegram-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-types
